# Generated by Django 5.0.6 on 2024-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
